apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipPool.name }}
  namespace: {{ .Values.ipPool.namespace }}
spec:
  addresses:
{{- range .Values.ipPool.addresses }}
    - {{ . }}
{{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2Advertisement.name }}
  namespace: {{ .Values.ipPool.namespace }}
spec:
  ipAddressPools:
    - {{ .Values.ipPool.name }}